seed: 0
exps_dir: 'experiments'
iter_log_interval: 1
iter_time_window: 100
model_save_interval: 1
backup:
model:
  name: PolyRegression
  parameters:
    num_outputs: 35
    pretrained: true
    backbone: 'efficientnet-b0'
    pred_category: false
loss_parameters:
  conf_weight: 1
  lower_weight: 1
  upper_weight: 1
  cls_weight: 0
  poly_weight: 300
batch_size: 16
epochs: 150
optimizer:
  name: Adam
  parameters:
    lr: 3.0e-4
lr_scheduler:
  name: CosineAnnealingLR
  parameters:
    T_max: 150
test_parameters:
  conf_threshold: 0.5
datasets:
  train:
    type: LaneDataset
    parameters:
      dataset: coco
      datasets:
        - root: datasets/apagadas1/train
          annotation: _annotations.coco.json
        - root: datasets/dia1/train
          annotation: _annotations.coco.json
        - root: datasets/noite1/train
          annotation: _annotations.coco.json
        - root: datasets/nevoeiro1/train
          annotation: _annotations.coco.json
      img_size: [360, 640]
      normalize: true
      aug_chance: 0.9090909090909091
      augmentations:
        - name: Affine
          parameters:
            rotate: !!python/tuple [-10, 10]
        - name: HorizontalFlip
          parameters:
            p: 0.5
        - name: CropToFixedSize
          parameters:
            width: 1152
            height: 648
  test:
    type: LaneDataset
    parameters:
      dataset: coco
      datasets:
        - root: datasets/apagadas2/train
          annotation: _annotations.coco.json
        - root: datasets/dia2/train
          annotation: _annotations.coco.json
        - root: datasets/noite2/train
          annotation: _annotations.coco.json
        - root: datasets/nevoeiro-noite2.coco-segmentation/train
          annotation: _annotations.coco.json
        - root: datasets/nevoeiro_noite_residual.coco-segmentation/train
          annotation: _annotations.coco.json
      img_size: [360, 640]
      normalize: true
      augmentations: []
